name: Coverage with JVM Flags

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-with-flags:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        jvm_flags:
          # Tier 1: Basic optimization flags
          - "-XX:+TieredCompilation"
          
          # Tier 2: GC optimization
          - "-XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+ParallelRefProcEnabled"
          
          # Tier 3: Memory optimization
          - "-XX:+UseCompressedOops -XX:+UseCompressedClassPointers -XX:+OptimizeStringConcat"
          
          # Tier 4: Combined optimizations
          - "-XX:+TieredCompilation -XX:+UseG1GC -XX:MaxGCPauseMillis=200"

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Validate JVM Flags
        run: |
          # Function to validate JVM flags
          validate_flags() {
            local flags="$1"
            local java_cmd="java $flags -version"
            
            if ! $java_cmd 2>/dev/null; then
              echo "Error: Invalid or unsupported JVM flags: $flags"
              return 1
            fi
            
            # Check for conflicting GC flags
            if [[ "$flags" == *"-XX:+UseParallelGC"* ]] && [[ "$flags" == *"-XX:+UseG1GC"* ]]; then
              echo "Error: Conflicting GC flags detected"
              return 1
            fi
            
            # Check for conflicting compilation flags
            if [[ "$flags" == *"-XX:-TieredCompilation"* ]] && [[ "$flags" == *"-XX:+TieredCompilation"* ]]; then
              echo "Error: Conflicting compilation flags detected"
              return 1
            fi
            
            return 0
          }
          
          if ! validate_flags "${{ matrix.jvm_flags }}"; then
            exit 1
          fi
          
          echo "JVM flags validated successfully: ${{ matrix.jvm_flags }}"

      - name: Document JVM Flag Purpose
        run: |
          echo "Running tests with JVM Flag: ${{ matrix.jvm_flags }}"
          echo "Flag Purpose:"
          case "${{ matrix.jvm_flags }}" in
            *"TieredCompilation"*)
              echo "- TieredCompilation: Enables multi-level JIT compilation for optimal performance"
              ;;
            *"UseG1GC"*)
              echo "- G1GC: Garbage-First Garbage Collector optimized for large heaps"
              echo "- MaxGCPauseMillis: Sets target pause time for GC"
              echo "- ParallelRefProcEnabled: Enables parallel reference processing"
              ;;
            *"UseCompressedOops"*)
              echo "- CompressedOops: Optimizes object references on 64-bit JVM"
              echo "- UseCompressedClassPointers: Optimizes class pointers"
              echo "- OptimizeStringConcat: Optimizes string concatenation operations"
              ;;
          esac

      - name: Verify Java Installation
        run: java -version

      - name: Clean and Compile
        run: ./mvnw -B clean compile

      - name: Run Tests with JaCoCo Coverage
        run: |
          # Sanitize flag name for file naming
          sanitized_flag=$(echo "${{ matrix.jvm_flags }}" | sed 's/[^-a-zA-Z0-9+._]/_/g' | tr ' ' '_')
          jacoco_exec_file="target/jacoco_${sanitized_flag}.exec"
          
          # Find JaCoCo agent path
          jacoco_agent_path="$(find ~/.m2/repository/org/jacoco -name "org.jacoco.agent*.jar" | head -n 1)"
          
          if [ ! -f "$jacoco_agent_path" ]; then
            echo "Error: JaCoCo agent not found"
            exit 1
          fi
          
          # Run tests with JaCoCo and JVM flags
          export MAVEN_OPTS="-javaagent:${jacoco_agent_path}=destfile=${jacoco_exec_file} ${{ matrix.jvm_flags }}"
          echo "Running with MAVEN_OPTS: $MAVEN_OPTS"
          
          # Run tests with retries for stability
          for i in {1..3}; do
            if ./mvnw -B test; then
              break
            fi
            if [ $i -eq 3 ]; then
              echo "Tests failed after 3 attempts"
              exit 1
            fi
            echo "Retrying tests... (attempt $((i+1)) of 3)"
            sleep 5
          done
          
          if [ ! -f "$jacoco_exec_file" ]; then
            echo "Error: JaCoCo execution data file not generated"
            exit 1
          fi

      - name: Generate Coverage Report
        run: |
          sanitized_flag=$(echo "${{ matrix.jvm_flags }}" | sed 's/[^-a-zA-Z0-9+._]/_/g' | tr ' ' '_')
          jacoco_exec_file="target/jacoco_${sanitized_flag}.exec"
          
          # Generate HTML and CSV reports
          ./mvnw jacoco:report -Djacoco.dataFile=${jacoco_exec_file}
          
          # Create flag-specific report directory
          report_dir="target/coverage-reports/${sanitized_flag}"
          mkdir -p "$report_dir"
          
          # Copy reports and add flag information
          cp -r target/site/jacoco/* "$report_dir/"
          echo "JVM Flags: ${{ matrix.jvm_flags }}" > "$report_dir/flags-info.txt"
          date >> "$report_dir/flags-info.txt"

      - name: Extract Coverage Metrics
        id: coverage
        run: |
          sanitized_flag=$(echo "${{ matrix.jvm_flags }}" | sed 's/[^-a-zA-Z0-9+._]/_/g' | tr ' ' '_')
          report_file="target/site/jacoco/jacoco.csv"
          
          if [ -f "$report_file" ]; then
            # Calculate coverage metrics
            total_lines=$(awk -F',' 'NR>1 {covered+=$5; missed+=$4} END {print covered+missed}' "$report_file")
            covered_lines=$(awk -F',' 'NR>1 {covered+=$5} END {print covered}' "$report_file")
            
            if [ "$total_lines" -gt 0 ]; then
              coverage=$((100 * covered_lines / total_lines))
              branch_coverage=$(awk -F',' 'NR>1 {covered+=$7; missed+=$6} END {printf "%.2f", (covered/(covered+missed))*100}' "$report_file")
              
              echo "Coverage Statistics for ${{ matrix.jvm_flags }}:"
              echo "Line Coverage: ${coverage}%"
              echo "Branch Coverage: ${branch_coverage}%"
              
              echo "COVERAGE=${coverage}" >> $GITHUB_ENV
              echo "BRANCH_COVERAGE=${branch_coverage}" >> $GITHUB_ENV
            else
              echo "No executable lines found"
              echo "COVERAGE=0" >> $GITHUB_ENV
              echo "BRANCH_COVERAGE=0" >> $GITHUB_ENV
            fi
          else
            echo "Coverage report not found"
            echo "COVERAGE=0" >> $GITHUB_ENV
            echo "BRANCH_COVERAGE=0" >> $GITHUB_ENV
          fi

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ strategy.job-index }}
          path: target/coverage-reports
          retention-days: 14

      - name: Report Coverage
        run: |
          echo "Coverage Summary for ${{ matrix.jvm_flags }}"
          echo "Line Coverage: ${{ env.COVERAGE }}%"
          echo "Branch Coverage: ${{ env.BRANCH_COVERAGE }}%"
          echo "Full report available in artifacts"

  coverage-summary:
    needs: test-with-flags
    runs-on: ubuntu-latest
    steps:
      - name: Download all coverage reports
        uses: actions/download-artifact@v4
        with:
          path: coverage-reports

      - name: Generate Summary
        run: |
          echo "# Coverage Summary" > coverage-summary.md
          echo "| JVM Flags | Line Coverage | Branch Coverage |" >> coverage-summary.md
          echo "|-----------|---------------|-----------------|" >> coverage-summary.md
          
          for report in coverage-reports/coverage-report-*/; do
            if [ -f "$report/jacoco.csv" ]; then
              flag_info=$(cat "$report/flags-info.txt" | head -n 1 | cut -d':' -f2-)
              line_coverage=$(awk -F',' 'NR>1 {covered+=$5; missed+=$4} END {printf "%.2f", (covered/(covered+missed))*100}' "$report/jacoco.csv")
              branch_coverage=$(awk -F',' 'NR>1 {covered+=$7; missed+=$6} END {printf "%.2f", (covered/(covered+missed))*100}' "$report/jacoco.csv")
              echo "| $flag_info | ${line_coverage}% | ${branch_coverage}% |" >> coverage-summary.md
            fi
          done

      - name: Upload Summary
        uses: actions/upload-artifact@v4
        with:
          name: coverage-summary
          path: coverage-summary.md
          retention-days: 14
